import { Roboto } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // You can specify the font weights you need
});

export const metadata = {
  title: "Aidroo: Explore Reviews",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={roboto.className}>
        {/* <ThemeProvider
          attribute="class"
          enableSystem
          themes={["light", "dark"]}
          disableTransitionOnChange
        > */}
        <AuthContextProvider>
          <main className="w-full ">{children}</main>
        </AuthContextProvider>

        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
